version: "3.9"

services:
  api:
    build: .
    container_name: web-analyzer-api
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  ui:
    build: .
    container_name: web-analyzer-ui
    ports:
      - "8501:8501"
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    volumes:
      - .:/app
